/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package courseSelection.coursegui;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.swing.JComponent;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

import courseSelection.constants.DISTRICT;
import courseSelection.constants.SCHEME;
import courseSelection.constants.UNIVERSITY;
import courseSelection.course.CourseAgent;
import courseSelection.ontology.District;
import courseSelection.ontology.University;
import jade.tools.sniffer.Agent;

/**
 *
 * @author NT
 */
public class CourseSelectionDialog extends javax.swing.JFrame {

	private Map<Integer, District> districtMap = new HashMap<>();
	private Map<Integer, University> universityMap = new HashMap<>();
	private Map<Integer, SCHEME> schemeMap = new HashMap<>();
	
    private List<OfferedUniversity> selectedUniversityList = new ArrayList<OfferedUniversity>();
    private List<SupportSchema> selectedSchemaList = new ArrayList<SupportSchema>();
    
    private CourseAgent agent;

    /**
     * Creates new form CourseSelectionDialog
     */
    public CourseSelectionDialog(CourseAgent agent) {
    	this.agent = agent;
    	setLookAndFeel();
        initComponents();
        setTitle("Course Selector");
        setResizable(false);
        setLocationRelativeTo(null);
        pack();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainPnel = new javax.swing.JPanel();
        formPanel = new javax.swing.JPanel();
        lbl_courseName = new javax.swing.JLabel();
        txt_courseName = new javax.swing.JTextField();
        lbl_offeredUniversities = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lst_offeredUniversities = new JList<OfferedUniversity>(
            new OfferedUniversity[] { new OfferedUniversity(UNIVERSITY.UniversityOfColombo.getName()),
                new OfferedUniversity(UNIVERSITY.UniversityOfPeradeniya.getName()),
                new OfferedUniversity(UNIVERSITY.UniversityOfMoratuwa.getName()),
                new OfferedUniversity(UNIVERSITY.UniversityOfKelaniya.getName()),
                new OfferedUniversity(UNIVERSITY.UniversityOfSriJayewardenepura.getName()),
                new OfferedUniversity(UNIVERSITY.UniversityOfRuhuna.getName()),
                new OfferedUniversity(UNIVERSITY.OpenUniversityOfSriLanka.getName()),
                new OfferedUniversity(UNIVERSITY.UniversityOfJaffna.getName()),
                new OfferedUniversity(UNIVERSITY.SouthEasternUniversityOfSriLanka.getName()),
                new OfferedUniversity(UNIVERSITY.RajarataUniversity.getName()),
                new OfferedUniversity(UNIVERSITY.SabaragamuwaUniversity.getName()),
                new OfferedUniversity(UNIVERSITY.EasternUniversity.getName()),
                new OfferedUniversity(UNIVERSITY.UniversityOfTheVisualAndPerformingArts.getName()),
                new OfferedUniversity(UNIVERSITY.WayambaUniversity.getName())});
        	
        lbl_districtZScore = new javax.swing.JLabel();
        lbl_supportedSchemas = new javax.swing.JLabel();
        districtPanel = new javax.swing.JPanel();
        lbl_ampara = new javax.swing.JLabel();
        lbl_anuradhapura = new javax.swing.JLabel();
        lbl_badulla = new javax.swing.JLabel();
        lbl_batticaloa = new javax.swing.JLabel();
        lbl_colombo = new javax.swing.JLabel();
        txt_ampara = new javax.swing.JTextField();
        txt_anuradhapura = new javax.swing.JTextField();
        txt_badulla = new javax.swing.JTextField();
        txt_batticaloa = new javax.swing.JTextField();
        txt_colombo = new javax.swing.JTextField();
        lbl_kalutara = new javax.swing.JLabel();
        lbl_kandy = new javax.swing.JLabel();
        lbl_kegalle = new javax.swing.JLabel();
        lbl_kilinochchi = new javax.swing.JLabel();
        lbl_kurunegala = new javax.swing.JLabel();
        txt_galle = new javax.swing.JTextField();
        txt_gampaha = new javax.swing.JTextField();
        txt_hambantota = new javax.swing.JTextField();
        txt_jaffna = new javax.swing.JTextField();
        txt_kalutara = new javax.swing.JTextField();
        lbl_nuwaraEliya = new javax.swing.JLabel();
        lbl_mullaitivu = new javax.swing.JLabel();
        lbl_polonnaruwa = new javax.swing.JLabel();
        lbl_monaragala = new javax.swing.JLabel();
        lbl_puttalam = new javax.swing.JLabel();
        txt_kandy = new javax.swing.JTextField();
        txt_kegalle = new javax.swing.JTextField();
        txt_kilinochchi = new javax.swing.JTextField();
        txt_kurunegala = new javax.swing.JTextField();
        txt_mannar = new javax.swing.JTextField();
        lbl_galle = new javax.swing.JLabel();
        lbl_gampaha = new javax.swing.JLabel();
        lbl_hambantota = new javax.swing.JLabel();
        lbl_vavuniya = new javax.swing.JLabel();
        txt_matale = new javax.swing.JTextField();
        txt_matara = new javax.swing.JTextField();
        txt_monaragala = new javax.swing.JTextField();
        txt_mullaitivu = new javax.swing.JTextField();
        lbl_jaffna = new javax.swing.JLabel();
        txt_nuwaraEliya = new javax.swing.JTextField();
        lbl_mannar = new javax.swing.JLabel();
        lbl_ratnapura = new javax.swing.JLabel();
        lbl_matale = new javax.swing.JLabel();
        lbl_trincomalee = new javax.swing.JLabel();
        lbl_matara = new javax.swing.JLabel();
        txt_polonnaruwa = new javax.swing.JTextField();
        txt_puttalam = new javax.swing.JTextField();
        txt_ratnapura = new javax.swing.JTextField();
        txt_trincomalee = new javax.swing.JTextField();
        txt_vavuniya = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        lst_supportedSchemas = new JList<SupportSchema>(new SupportSchema[]
            { new SupportSchema(SCHEME.ART.getName()),
                new SupportSchema(SCHEME.COMMERSE.getName()),
                new SupportSchema(SCHEME.SCIENCE.getName())});
        buttonPanel = new javax.swing.JPanel();
        btn_add = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_courseName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_courseName.setText("Course Name:");

        lbl_offeredUniversities.setText("Offered Universities:");

        lst_offeredUniversities.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lst_offeredUniversities.setCellRenderer(new OfferedUniversityCheckboxListRenderer());
        lst_offeredUniversities.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lst_offeredUniversitiesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lst_offeredUniversities);

        lbl_districtZScore.setText("District Z-Scores:");

        lbl_supportedSchemas.setText("Supported Schemas:");

        java.awt.GridBagLayout districtPanelLayout = new java.awt.GridBagLayout();
        districtPanelLayout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        districtPanelLayout.rowHeights = new int[] {0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0};
        districtPanel.setLayout(districtPanelLayout);

        lbl_ampara.setText("Ampara");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        districtPanel.add(lbl_ampara, gridBagConstraints);

        lbl_anuradhapura.setText("Anuradhapura");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        districtPanel.add(lbl_anuradhapura, gridBagConstraints);

        lbl_badulla.setText("Badulla");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        districtPanel.add(lbl_badulla, gridBagConstraints);

        lbl_batticaloa.setText("Batticaloa");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        districtPanel.add(lbl_batticaloa, gridBagConstraints);

        lbl_colombo.setText("Colombo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        districtPanel.add(lbl_colombo, gridBagConstraints);

        txt_ampara.setMinimumSize(new java.awt.Dimension(40, 20));
        txt_ampara.setPreferredSize(new java.awt.Dimension(40, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        districtPanel.add(txt_ampara, gridBagConstraints);

        txt_anuradhapura.setPreferredSize(new java.awt.Dimension(40, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        districtPanel.add(txt_anuradhapura, gridBagConstraints);

        txt_badulla.setPreferredSize(new java.awt.Dimension(40, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        districtPanel.add(txt_badulla, gridBagConstraints);

        txt_batticaloa.setPreferredSize(new java.awt.Dimension(40, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        districtPanel.add(txt_batticaloa, gridBagConstraints);

        txt_colombo.setPreferredSize(new java.awt.Dimension(40, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        districtPanel.add(txt_colombo, gridBagConstraints);

        lbl_kalutara.setText("Kalutara");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        districtPanel.add(lbl_kalutara, gridBagConstraints);

        lbl_kandy.setText("Kandy");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        districtPanel.add(lbl_kandy, gridBagConstraints);

        lbl_kegalle.setText("Kegalle");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        districtPanel.add(lbl_kegalle, gridBagConstraints);

        lbl_kilinochchi.setText("Kilinochchi");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        districtPanel.add(lbl_kilinochchi, gridBagConstraints);

        lbl_kurunegala.setText("Kurunegala");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        districtPanel.add(lbl_kurunegala, gridBagConstraints);

        txt_galle.setPreferredSize(new java.awt.Dimension(40, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        districtPanel.add(txt_galle, gridBagConstraints);

        txt_gampaha.setPreferredSize(new java.awt.Dimension(40, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        districtPanel.add(txt_gampaha, gridBagConstraints);

        txt_hambantota.setPreferredSize(new java.awt.Dimension(40, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        districtPanel.add(txt_hambantota, gridBagConstraints);

        txt_jaffna.setPreferredSize(new java.awt.Dimension(40, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        districtPanel.add(txt_jaffna, gridBagConstraints);

        txt_kalutara.setPreferredSize(new java.awt.Dimension(40, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        districtPanel.add(txt_kalutara, gridBagConstraints);

        lbl_nuwaraEliya.setText("Nuwara Eliya");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        districtPanel.add(lbl_nuwaraEliya, gridBagConstraints);

        lbl_mullaitivu.setText("Mullaitivu");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        districtPanel.add(lbl_mullaitivu, gridBagConstraints);

        lbl_polonnaruwa.setText("Polonnaruwa");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        districtPanel.add(lbl_polonnaruwa, gridBagConstraints);

        lbl_monaragala.setText("Monaragala");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        districtPanel.add(lbl_monaragala, gridBagConstraints);

        lbl_puttalam.setText("Puttalam");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        districtPanel.add(lbl_puttalam, gridBagConstraints);

        txt_kandy.setPreferredSize(new java.awt.Dimension(40, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        districtPanel.add(txt_kandy, gridBagConstraints);

        txt_kegalle.setPreferredSize(new java.awt.Dimension(40, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        districtPanel.add(txt_kegalle, gridBagConstraints);

        txt_kilinochchi.setPreferredSize(new java.awt.Dimension(40, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        districtPanel.add(txt_kilinochchi, gridBagConstraints);

        txt_kurunegala.setPreferredSize(new java.awt.Dimension(40, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        districtPanel.add(txt_kurunegala, gridBagConstraints);

        txt_mannar.setPreferredSize(new java.awt.Dimension(40, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        districtPanel.add(txt_mannar, gridBagConstraints);

        lbl_galle.setText("Galle");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        districtPanel.add(lbl_galle, gridBagConstraints);

        lbl_gampaha.setText("Gampaha");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        districtPanel.add(lbl_gampaha, gridBagConstraints);

        lbl_hambantota.setText("Hambantota");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        districtPanel.add(lbl_hambantota, gridBagConstraints);

        lbl_vavuniya.setText("Vavuniya");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        districtPanel.add(lbl_vavuniya, gridBagConstraints);

        txt_matale.setPreferredSize(new java.awt.Dimension(40, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        districtPanel.add(txt_matale, gridBagConstraints);

        txt_matara.setPreferredSize(new java.awt.Dimension(40, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        districtPanel.add(txt_matara, gridBagConstraints);

        txt_monaragala.setPreferredSize(new java.awt.Dimension(40, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        districtPanel.add(txt_monaragala, gridBagConstraints);

        txt_mullaitivu.setPreferredSize(new java.awt.Dimension(40, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        districtPanel.add(txt_mullaitivu, gridBagConstraints);

        lbl_jaffna.setText("Jaffna");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        districtPanel.add(lbl_jaffna, gridBagConstraints);

        txt_nuwaraEliya.setPreferredSize(new java.awt.Dimension(40, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        districtPanel.add(txt_nuwaraEliya, gridBagConstraints);

        lbl_mannar.setText("Mannar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        districtPanel.add(lbl_mannar, gridBagConstraints);

        lbl_ratnapura.setText("Ratnapura");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        districtPanel.add(lbl_ratnapura, gridBagConstraints);

        lbl_matale.setText("Matale");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        districtPanel.add(lbl_matale, gridBagConstraints);

        lbl_trincomalee.setText("Trincomalee");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        districtPanel.add(lbl_trincomalee, gridBagConstraints);

        lbl_matara.setText("Matara");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        districtPanel.add(lbl_matara, gridBagConstraints);

        txt_polonnaruwa.setPreferredSize(new java.awt.Dimension(40, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        districtPanel.add(txt_polonnaruwa, gridBagConstraints);

        txt_puttalam.setPreferredSize(new java.awt.Dimension(40, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        districtPanel.add(txt_puttalam, gridBagConstraints);

        txt_ratnapura.setPreferredSize(new java.awt.Dimension(40, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        districtPanel.add(txt_ratnapura, gridBagConstraints);

        txt_trincomalee.setPreferredSize(new java.awt.Dimension(40, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        districtPanel.add(txt_trincomalee, gridBagConstraints);

        txt_vavuniya.setPreferredSize(new java.awt.Dimension(40, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        districtPanel.add(txt_vavuniya, gridBagConstraints);

        lst_supportedSchemas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lst_supportedSchemas.setCellRenderer(new SchemaCheckboxListRenderer());
        lst_supportedSchemas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lst_supportedSchemasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lst_supportedSchemas);

        javax.swing.GroupLayout formPanelLayout = new javax.swing.GroupLayout(formPanel);
        formPanel.setLayout(formPanelLayout);
        formPanelLayout.setHorizontalGroup(
            formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formPanelLayout.createSequentialGroup()
                        .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_courseName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_offeredUniversities, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_districtZScore, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbl_supportedSchemas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_courseName)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2)))
                    .addGroup(formPanelLayout.createSequentialGroup()
                        .addComponent(districtPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        formPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lbl_courseName, lbl_districtZScore, lbl_offeredUniversities, lbl_supportedSchemas});

        formPanelLayout.setVerticalGroup(
            formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_courseName)
                    .addComponent(txt_courseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_offeredUniversities))
                .addGap(18, 18, 18)
                .addComponent(lbl_districtZScore)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(districtPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_supportedSchemas))
                .addGap(83, 83, 83))
        );

        btn_add.setText("Add");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_cancel.setText("Cancel");

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_cancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_add)
                .addContainerGap())
        );

        buttonPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_add, btn_cancel});

        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_add)
                    .addComponent(btn_cancel))
                .addContainerGap())
        );

        javax.swing.GroupLayout mainPnelLayout = new javax.swing.GroupLayout(mainPnel);
        mainPnel.setLayout(mainPnelLayout);
        mainPnelLayout.setHorizontalGroup(
            mainPnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPnelLayout.createSequentialGroup()
                .addGroup(mainPnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(buttonPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mainPnelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(formPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        mainPnelLayout.setVerticalGroup(
            mainPnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPnelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(formPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPnel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPnel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lst_offeredUniversitiesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lst_offeredUniversitiesMouseClicked
        JList<OfferedUniversity> offeredUniversityList = (JList<OfferedUniversity>) evt.getSource();

        // Get index of item clicked
        int index = offeredUniversityList.locationToIndex(evt.getPoint());
        OfferedUniversity offeredUniversity = (OfferedUniversity) offeredUniversityList.getModel().getElementAt(index);

        // Toggle selected state
        offeredUniversity.setIsSelected(!offeredUniversity.isSelected());

        // Repaint cell
        offeredUniversityList.repaint(offeredUniversityList.getCellBounds(index, index));

        if (offeredUniversity.isSelected()) {
            selectedUniversityList.add(offeredUniversity);
        } else {
            selectedUniversityList.remove(offeredUniversity);
        }
        System.out.println("DEBUG: University: " + offeredUniversity.toString() + " isSelected: " + offeredUniversity.isSelected());
        System.out.println("DEBUG: selectedUniversityList: " + selectedUniversityList);
    }//GEN-LAST:event_lst_offeredUniversitiesMouseClicked

    private void lst_supportedSchemasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lst_supportedSchemasMouseClicked
        JList<SupportSchema> supportSchemaList = (JList<SupportSchema>) evt.getSource();

        // Get index of item clicked
        int index = supportSchemaList.locationToIndex(evt.getPoint());
        SupportSchema supportSchema = (SupportSchema) supportSchemaList.getModel().getElementAt(index);

        // Toggle selected state
        supportSchema.setIsSelected(!supportSchema.isSelected());

        // Repaint cell
        supportSchemaList.repaint(supportSchemaList.getCellBounds(index, index));

        if (supportSchema.isSelected()) {
            selectedSchemaList.add(supportSchema);
        } else {
            selectedSchemaList.remove(supportSchema);
        }
        System.out.println("DEBUG: Schema: " + supportSchema.toString() + " isSelected: " + supportSchema.isSelected());
        System.out.println("DEBUG: selectedSchemaList: " + selectedSchemaList);
    }//GEN-LAST:event_lst_supportedSchemasMouseClicked
    
    private void addToDistrictMap(int id, String zScore) {
    	District d = new District();
    	d.setId(id);
    	d.setDistrictName(DISTRICT.getById(id).toString());
    	d.setzScore(Float.parseFloat(zScore));
    	districtMap.put(id, d);
    }

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        
    	
    	String courseName = txt_courseName.getText();

        String z_score_ampara = txt_ampara.getText();
        addToDistrictMap(20, txt_ampara.getText());
        
        String z_score_anuradhapura = txt_anuradhapura.getText();
        addToDistrictMap(11, txt_anuradhapura.getText());
        
        String z_score_badulla = txt_badulla.getText();
        addToDistrictMap(21, txt_badulla.getText());
        
        String z_score_batticaloa = txt_batticaloa.getText();
        addToDistrictMap(19, txt_batticaloa.getText());
        
        String z_score_colombo = txt_colombo.getText();
        addToDistrictMap(9, txt_colombo.getText());
        
        String z_score_galle = txt_galle.getText();
        addToDistrictMap(25, txt_galle.getText());
        
        String z_score_gampaha = txt_gampaha.getText();
        addToDistrictMap(8, txt_gampaha.getText());
        
        String z_score_hambantota = txt_hambantota.getText();
        addToDistrictMap(23, txt_hambantota.getText());
        
        String z_score_jaffna = txt_jaffna.getText();
        addToDistrictMap(1, txt_jaffna.getText());
        
        String z_score_kalutara = txt_kalutara.getText();
        addToDistrictMap(10, txt_kalutara.getText());
        
        String z_score_kandy = txt_kandy.getText();
        addToDistrictMap(14, txt_kandy.getText());
        
        String z_score_kegalle = txt_kegalle.getText();
        addToDistrictMap(16, txt_kegalle.getText());
        
        String z_score_kilinochchi = txt_kilinochchi.getText();
        addToDistrictMap(2, txt_kilinochchi.getText());
        
        String z_score_kurunegala = txt_kurunegala.getText();
        addToDistrictMap(7, txt_kurunegala.getText());
        
        String z_score_mannar = txt_mannar.getText();
        addToDistrictMap(3, txt_mannar.getText());
        
        String z_score_matale = txt_matale.getText();
        addToDistrictMap(13, txt_matale.getText());
        
        String z_score_matara = txt_matara.getText();
        addToDistrictMap(24, txt_matara.getText());
        
        String z_score_monaragala = txt_monaragala.getText();
        addToDistrictMap(22, txt_monaragala.getText());
        
        String z_score_mullaitivu = txt_mullaitivu.getText();
        addToDistrictMap(4, txt_mullaitivu.getText());
        
        String z_score_nuwaraEliya = txt_nuwaraEliya.getText();
        addToDistrictMap(15, txt_nuwaraEliya.getText());
        
        String z_score_polonnaruwa = txt_polonnaruwa.getText();
        addToDistrictMap(12, txt_polonnaruwa.getText());
        
        String z_score_puttalam = txt_puttalam.getText();
        addToDistrictMap(6, txt_puttalam.getText());
        
        String z_score_ratnapura = txt_ratnapura.getText();
        addToDistrictMap(17, txt_ratnapura.getText());
        
        String z_score_trincomalee = txt_trincomalee.getText();
        addToDistrictMap(18, txt_trincomalee.getText());
        
        String z_score_vavuniya = txt_vavuniya.getText();
        addToDistrictMap(5, txt_vavuniya.getText());

        if (courseName == null || courseName.equals("")) {
            JOptionPane.showMessageDialog(this, "Course Name can not be empty!",
                    "ERROR", JOptionPane.ERROR_MESSAGE);
            txt_courseName.grabFocus();

        } else if (selectedUniversityList.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select at least one university!",
                    "ERROR", JOptionPane.ERROR_MESSAGE);
        } else if (selectedSchemaList.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select at least one Scheme!",
                    "ERROR", JOptionPane.ERROR_MESSAGE);
        } /*else if (!validateDistrictZScore()) {
            JOptionPane.showMessageDialog(this, "Please set at least one Z-Score for a district!",
                    "ERROR", JOptionPane.ERROR_MESSAGE);
        }*/
        
        for(OfferedUniversity u : selectedUniversityList) {
        	UNIVERSITY uEnum = UNIVERSITY.getByName(u.getUniversityName());
        	University uni = new University();
        	uni.setId(uEnum.getId());
        	uni.setUniversityName(uEnum.getName());
        	
        	universityMap.put(uEnum.getId(), uni);
        }
        
        for(SupportSchema s : selectedSchemaList) {
        	SCHEME sEnum = SCHEME.getByName(s.getSchemaName());
        	schemeMap.put(sEnum.getId(), sEnum);
        }
        
        agent.updateCourseAgent(courseName, universityMap, districtMap, schemeMap);
        
    }//GEN-LAST:event_btn_addActionPerformed
    
    public void showGui(){
    	setVisible(true);
    }

    private boolean validateDistrictZScore() {
        for (int i = 0; i < districtPanel.getComponentCount(); i++) {
            JComponent child = (JComponent) districtPanel.getComponent(i);
            if (child instanceof JTextField) {
                System.out.println("DEBUG: JTextField: " + i);
                if (((JTextField) child).getText().equals("")) {
                    return false;
                }
            }
        }

        return true;
    }

    /**
     * @param args the command line arguments
     */
    public void setLookAndFeel() {//static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CourseSelectionDialog.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CourseSelectionDialog.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CourseSelectionDialog.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CourseSelectionDialog.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


/*        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CourseSelectionDialog(new CourseAgent()).setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel districtPanel;
    private javax.swing.JPanel formPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_ampara;
    private javax.swing.JLabel lbl_anuradhapura;
    private javax.swing.JLabel lbl_badulla;
    private javax.swing.JLabel lbl_batticaloa;
    private javax.swing.JLabel lbl_colombo;
    private javax.swing.JLabel lbl_courseName;
    private javax.swing.JLabel lbl_districtZScore;
    private javax.swing.JLabel lbl_galle;
    private javax.swing.JLabel lbl_gampaha;
    private javax.swing.JLabel lbl_hambantota;
    private javax.swing.JLabel lbl_jaffna;
    private javax.swing.JLabel lbl_kalutara;
    private javax.swing.JLabel lbl_kandy;
    private javax.swing.JLabel lbl_kegalle;
    private javax.swing.JLabel lbl_kilinochchi;
    private javax.swing.JLabel lbl_kurunegala;
    private javax.swing.JLabel lbl_mannar;
    private javax.swing.JLabel lbl_matale;
    private javax.swing.JLabel lbl_matara;
    private javax.swing.JLabel lbl_monaragala;
    private javax.swing.JLabel lbl_mullaitivu;
    private javax.swing.JLabel lbl_nuwaraEliya;
    private javax.swing.JLabel lbl_offeredUniversities;
    private javax.swing.JLabel lbl_polonnaruwa;
    private javax.swing.JLabel lbl_puttalam;
    private javax.swing.JLabel lbl_ratnapura;
    private javax.swing.JLabel lbl_supportedSchemas;
    private javax.swing.JLabel lbl_trincomalee;
    private javax.swing.JLabel lbl_vavuniya;
    private javax.swing.JList<OfferedUniversity> lst_offeredUniversities;
    private javax.swing.JList<SupportSchema> lst_supportedSchemas;
    private javax.swing.JPanel mainPnel;
    private javax.swing.JTextField txt_ampara;
    private javax.swing.JTextField txt_anuradhapura;
    private javax.swing.JTextField txt_badulla;
    private javax.swing.JTextField txt_batticaloa;
    private javax.swing.JTextField txt_colombo;
    private javax.swing.JTextField txt_courseName;
    private javax.swing.JTextField txt_galle;
    private javax.swing.JTextField txt_gampaha;
    private javax.swing.JTextField txt_hambantota;
    private javax.swing.JTextField txt_jaffna;
    private javax.swing.JTextField txt_kalutara;
    private javax.swing.JTextField txt_kandy;
    private javax.swing.JTextField txt_kegalle;
    private javax.swing.JTextField txt_kilinochchi;
    private javax.swing.JTextField txt_kurunegala;
    private javax.swing.JTextField txt_mannar;
    private javax.swing.JTextField txt_matale;
    private javax.swing.JTextField txt_matara;
    private javax.swing.JTextField txt_monaragala;
    private javax.swing.JTextField txt_mullaitivu;
    private javax.swing.JTextField txt_nuwaraEliya;
    private javax.swing.JTextField txt_polonnaruwa;
    private javax.swing.JTextField txt_puttalam;
    private javax.swing.JTextField txt_ratnapura;
    private javax.swing.JTextField txt_trincomalee;
    private javax.swing.JTextField txt_vavuniya;
    // End of variables declaration//GEN-END:variables
}
